# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-lastest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '0e530a5c-6e1d-435c-a43c-26517d9e4239'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'repro2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM/azuredeploy.son'
    overrideParameters: '-projectName Infra Deploy -linkedTemplateUri https://github.com/jobeehichoya/ARM/blob/master/azuredeploy.json'
    deploymentMode: 'Incremental'
